plugins {
    id 'java'
    id 'war'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Основной API Jakarta EE
    compileOnly 'jakarta.platform:jakarta.jakartaee-web-api:10.0.0'

    // Драйвер БД и ORM
    implementation 'org.postgresql:postgresql:42.2.5'
    implementation 'org.hibernate:hibernate-core:6.4.8.Final'

    // Утилиты
    implementation 'org.mindrot:jbcrypt:0.4'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.15.2'

    // JWT и ПРИЧИНА ОШИБКИ (JAXB)
    implementation 'io.jsonwebtoken:jjwt:0.9.1'
    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.1'

    // Ломбок
    compileOnly 'org.projectlombok:lombok:1.18.28'
    annotationProcessor 'org.projectlombok:lombok:1.18.28'
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    options.compilerArgs.addAll(['--release', '17'])
}